### ISSUE TITLE
Agregar La Cuentoneta al Hacktoberfest

### ISSUE THREAD

**Issue by erikgiovani** [cuentoneta/cuentoneta#1002]
### Recursos

- [Hacktoberfest](https://hacktoberfest.com/participation/)
- https://dev.to/mishmanners/hacktoberfest-is-here-how-do-you-get-involved-jp7

**Comment by rolivencia** [comment]
No he tenido tiempo para enviar la solicitud. Lo dejaremos para la próxima edición.
