### ISSUE TITLE
Eliminar archivo .eslintrc.json

### ISSUE THREAD

**Issue by erikgiovani** [cuentoneta/cuentoneta#1012]
### Descripción

Esperar el soporte total de eslint 9 de los plugins para borrar el archivo `.eslintrc.json` y quedarnos solo con el `eslint.config.js` y remover el uso de FlatCompat para tener un archivo de configuración mas limpio.

#### Plugins a actualizar
- [x] eslint-plugin-storybook
- [x] eslint-plugin-testing-library
- [x] eslint-plugin-jest-dom

### Recursos
* [Migration guide](https://eslint.org/docs/latest/use/migrate-to-9.0.0)

#### Estado de los plugins a migrar

- [storybook/recommended](https://github.com/storybookjs/eslint-plugin-storybook), el issue se está siguiendo en [Suport ESLint v9 ](https://github.com/storybookjs/eslint-plugin-storybook/issues/157) ✅.
- [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint) ya tiene soporte según este PR [feat: support ESLint v9](https://github.com/typescript-eslint/typescript-eslint/pull/9002) ✅.
- [angular-eslint](https://github.com/angular-eslint/angular-eslint) ya tiene soporte, se está siguiendo en [eslint v9.0.0 compatibility](https://github.com/angular-eslint/angular-eslint/issues/1755) ✅.

Como referencia, en el repo de eslint están siguiendo los plugins y su soporte, [Tracking: ESLint v9 support](https://github.com/eslint/eslint/issues/18391).

**Comment by rolivencia** [comment]
¿Podremos tener la lista de todos los plugins a migrar? De esa manera podemos ir haciendo una migración ordenada.

**Comment by Addin** [comment]
Acá la tienes Rami.

- [storybook/recommended](https://github.com/storybookjs/eslint-plugin-storybook), el issue se está siguiendo en [Suport ESLint v9 ](https://github.com/storybookjs/eslint-plugin-storybook/issues/157) ❌.
- [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint) ya tiene soporte según este PR [feat: support ESLint v9](https://github.com/typescript-eslint/typescript-eslint/pull/9002) ✅.
- [angular-eslint](https://github.com/angular-eslint/angular-eslint) ya tiene soporte, se está siguiendo en [eslint v9.0.0 compatibility](https://github.com/angular-eslint/angular-eslint/issues/1755) ✅.

Como referencia, en el repo de eslint están trackeando los plugins y su soporte, [Tracking: ESLint v9 support(https://github.com/eslint/eslint/issues/18391)

**Comment by ErikGIovani** [comment]
> Acá la tienes Rami.
> 
> * [storybook/recommended](https://github.com/storybookjs/eslint-plugin-storybook), el issue se está siguiendo en [Suport ESLint v9 ](https://github.com/storybookjs/eslint-plugin-storybook/issues/157) ❌.
> * [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint) ya tiene soporte según este PR [feat: support ESLint v9](https://github.com/typescript-eslint/typescript-eslint/pull/9002) ✅.
> * [angular-eslint](https://github.com/angular-eslint/angular-eslint) ya tiene soporte, se está siguiendo en [eslint v9.0.0 compatibility](https://github.com/angular-eslint/angular-eslint/issues/1755) ✅.
> 
> Como referencia, en el repo de eslint están siguiendo los plugins y su soporte, [Tracking: ESLint v9 support](https://github.com/eslint/eslint/issues/18391).

Buena referencia 👌

**Comment by ErikGIovani** [comment]
> ¿Podremos tener la lista de todos los plugins a migrar? De esa manera podemos ir haciendo una migración ordenada.

Ready 👍

**Comment by rolivencia** [comment]
Parece que ya tienen lista la PR para proceder con la actualización faltante en el repo de **[storybookjs/eslint-plugin-storybook](https://github.com/storybookjs/eslint-plugin-storybook)**: https://github.com/storybookjs/eslint-plugin-storybook/pull/156

**Comment by ErikGIovani** [comment]
> Parece que ya tienen lista la PR para proceder con la actualización faltante en el repo de **[storybookjs/eslint-plugin-storybook](https://github.com/storybookjs/eslint-plugin-storybook)**: [storybookjs/eslint-plugin-storybook#156](https://github.com/storybookjs/eslint-plugin-storybook/pull/156)
> 
> cc @ErikGIovani @Addin

Excelente 🥳, solo falta  https://github.com/testing-library/eslint-plugin-testing-library/pull/928

**Comment by erikgiovani** [comment]
@rolivencia hace tres días hicieron merge del pull request de eslint-plugin-testing-library para el soporte de eslint 9, espero la actualización de nx y angular y empiezo con el issue en caso de que existan cambios con alguna de sus dependencias 👍

**Comment by rolivencia** [comment]
Listo el trabajo de #1035 para la actualización de Angular @erikgiovani. Tuve que proceder con la actualización a ESLint 9, y la de los plugins, debido a que sino me era imposible actualizar Nx a la última versión.

La dependencia `eslint-plugin-testing-library` está dando un warning por incompatibilidad de versiones. Tenlo en cuenta a la hora de abordar este issue, dado que quizá el soporte está cerca. En todo caso, si lo crees conveniente, podemos dejar un issue abierto específicamente para abordar este tema.

**Comment by erikgiovani** [comment]
@rolivencia gracias por la recomendación, lo tendré en cuenta 🥳
