### ISSUE TITLE
Refactorización de BioSummaryCardComponent usando AuthorTeaserComponent

### ISSUE THREAD

**Issue by dylanson25** [cuentoneta/cuentoneta#1030]
### ¿Existe un problema similar reportado?

- [ ] Existe un problema similar
- [X] Es un problema completamente nuevo

### Descripción del problema

Actualmente, en el componente `BioSummaryCardComponent`, se repite la estructura que muestra los datos del autor, como su imagen, nombre y nacionalidad, los cuales también están presentes en el componente `AuthorTeaserComponent`. Esto genera duplicidad de código.

### Pasos para reproducir el problema

 -

### Comportamiento esperado

Se debe modificar el `BioSummaryCardComponent` para que reutilice el componente `AuthorTeaserComponent`.  El `AuthorTeaserComponent` deberá recibir un atributo de tamaño (size) para adaptarse a diferentes contextos de uso (como el tamaño que necesita `BioSummaryCardComponent` y el de `PublicationCardComponent`).

**Comment by dylanson25** [comment]
@rolivencia No me permite asignartelo. :c

**Comment by rolivencia** [comment]
Listo, ya me lo asigné. No tienes permisos para hacerlo, lo cual es esperable. Perdón por la confusión.
