### ISSUE TITLE
Centralizar los colores hardcodeados en los ficheros

### ISSUE THREAD

**Issue by ErikGIovani** [cuentoneta/cuentoneta#232]
## Los siguientes ficheros cuentan con los colores hardcodeados:

- [share-content.component.html](https://github.com/rolivencia/cuentoneta/blob/master/src/app/components/share-content/share-content.component.html)
- [story-card-skelleton.component.html](https://github.com/rolivencia/cuentoneta/blob/master/src/app/components/story-card-skeleton/story-card-skeleton.component.html)
- [story-list-card-deck.component.html](https://github.com/rolivencia/cuentoneta/blob/master/src/app/components/story-list-card-deck/story-list-card-deck.component.html)
- [story-navigation-bar.component.html](https://github.com/rolivencia/cuentoneta/blob/master/src/app/components/story-navigation-bar/story-navigation-bar.component.html)
- [story.component.html](https://github.com/rolivencia/cuentoneta/blob/master/src/app/pages/story/story.component.html)

**Comment by ErikGIovani** [comment]
> ¿Todos los colores hardcoded que tenemos coinciden con los skeletons? @ErikGIovani

Es correcto, el color es #D4D4D8 👍

**Comment by ErikGIovani** [comment]
> Encontré este post de StackOverflow para algunas ideas vía Tailwind, a fin de centralizar estos colores: https://stackoverflow.com/questions/61118060/how-to-access-tailwind-colors-from-javascript

Me parece buena idea 🥳, también podemos aprovechar el styles que tiene cada componente y desde ahí modificar el color directamente con tailwind, así en caso de querer cambiar a la versión 4 de tailwind se podría hacer ya que no se dependería de el archivo tailwind.config.

No se que te parece?

https://www.npmjs.com/package/ngx-skeleton-loader#%EF%B8%8F-this-is-here-only-as-a-documentation-but-its-not-encouraged-to-be-used-please-consider-use-it-with-caution-%EF%B8%8F

**Comment by rolivencia** [comment]
Experimentemos a ver qué sale. Lo muevo para el próximo milestone.

**Comment by ErikGIovani** [comment]
> Experimentemos a ver qué sale. Lo muevo para el próximo milestone.

Perfecto 🚀
