### ISSUE TITLE
Agregar accesibilidad para los idiomas.

### ISSUE THREAD

**Issue by ErikGIovani** [cuentoneta/cuentoneta#296]
# Descripción

Para mejorar la accesibilidad en los lectores de pantalla y adaptar la web a distintos idiomas se requiere hacer algunos ajustes tanto en sanity,  como a nivel de lógica de la web para poder identificar y consumir el contenido en distintos idiomas.

Issue de Referencia: https://github.com/rolivencia/cuentoneta/issues/152#issue-1631321990

# Requerimientos

- [x] #317
- [x] Determinar desde los schemas de Sanity cuál es el idioma de una Storylist.
- [x] Ídem para cada Story particular.
- [x] Agregar documentación para los modelos de las entidades del sistema.

# Recursos

* https://www.seoptimer.com/es/blog/html-lang/

* https://developer.mozilla.org/es/docs/Web/HTML/Global_attributes/lang

**Comment by rolivencia** [comment]
Agrego dos ítems para tener en cuenta:
- Determinar desde los schemas de Sanity cuál es el idioma de una Storylist.
- Ídem para cada Story particular.

**Comment by ErikGIovani** [comment]
> Agrego dos ítems para tener en cuenta:
> - Determinar desde los schemas de Sanity cuál es el idioma de una Storylist.
> - Ídem para cada Story particular.

Ya los agregé a los requerimientos del issue,  si quieres puedes cambiar la descripción del issue por algo que sea más entendible 👍

**Comment by rolivencia** [comment]
Cambio a milestone 2.1

**Comment by rolivencia** [comment]
¿Movemos este a la 2.2 @ErikGIovani? Para no andar corriendo detrás de este issue para lanzar la 2.1

**Comment by ErikGIovani** [comment]
> ¿Movemos este a la 2.2 @ErikGIovani? Para no andar corriendo detrás de este issue para lanzar la 2.1

Dale 👍

**Comment by rolivencia** [comment]
Creo que estamos en condiciones de cerrar este @ErikGIovani. Cuando puedas chequéalo. Me quedan dudas del último check, dado que no comprendo del todo a qué se refiere.

**Comment by ErikGIovani** [comment]
> Creo que estamos en condiciones de cerrar este @ErikGIovani. Cuando puedas chequéalo. Me quedan dudas del último check, dado que no comprendo del todo a qué se refiere.

Habías comentado algo sobre documentar los esquemas de sanity 👍

**Comment by ErikGIovani** [comment]
Si quieres procedemos a cerrarlo, ya están las importantes

**Comment by rolivencia** [comment]
Procedo a cerrar el issue.
