### ISSUE TITLE
Cambiar dinámicamente atributo lang según idioma de story o storylist al que se accede

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#317]
# Descripción

Nativamente La Cuentoneta está desarrollada para hispanoablantes. Sin embargo, con la inclusión de la storylist del grupo de estudio de inglés de FEC se presenta la necesidad de actualizar el atributo `lang` de las páginas que refieran a stories o storylists en otros idiomas.

### Investigación
- [x] Definir cómo proceder con el diseño de una solución que permita actualizar atributos `lang` de manera dinámica para accesibilidad del usuario.
- [x] Definir cómo proceder para permitir acceso mediante OG para brindar esta información a buscadores y frente a requests que requieran SSR.

### Implementación en Componentes 
- [x] BioSummaryCardComponent
- [x] StoryComponent
- [x] StoryCardComponent
- [x] StorylistComponent
- [x] StoryNavigationBarComponent

## Issues relacionados
* Para poder trabajar en este issue, es necesario tener completado el issue #349 

## Recursos
- https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang

**Comment by ErikGIovani** [comment]
Sanity tiene un plugin para internacionalización:

https://www.sanity.io/plugins/document-internationalization

**Comment by rolivencia** [comment]
Muevo este issue a la 2.2

**Comment by rolivencia** [comment]
@ErikGIovani, dado que podemos saber cuál es el idioma de una storylist y de una story particular, podemos trabajar en este issue.

Supongo que puede trabajarse haciendo uso del provider `Meta`, el cual ya hemos usado en directivas y componentes de la app.

Está desbloqueado para comenzar a trabajarlo. Muevo el issue al nuevo milestone `2.3.2`

**Comment by ErikGIovani** [comment]
> @ErikGIovani, dado que podemos saber cuál es el idioma de una storylist y de una story particular, podemos trabajar en este issue.
> 
> Supongo que puede trabajarse haciendo uso del provider `Meta`, el cual ya hemos usado en directivas y componentes de la app.
> 
> Está desbloqueado para comenzar a trabajarlo. Muevo el issue al nuevo milestone `2.3.2`

El problema del provider Meta es que solo sirve para meta tags y el lang es un atributo 😢, estuve leyendo que se puede hacer inyectando el Document de Angular para poder setear atributos y valores en el tag html de manera dinámica, pero habría problemas con los lectores de pantalla con los textos en español.

A mi me ocurre cambiar el tag div con la class main-container por un tag semántico como main y agregar el atributo lang con el idioma de la historia en ese main, el problema que le veo a mi solución es que tendríamos que cambiar el texto **Ver más** de las sidebar por un texto en inglés o español dependiendo el caso, también el texto **Biografía** y **Recurso Original** que aparecen en la biografía y la palabra **minutos de lectura** que aparece al inicio de la historia, con eso solo agregaríamos el lang="es" en el tag html en el html plano y el texto que se encuentra en inglés quedaría dentro del tag main con su lang dinámico.

Lo malo es que no se me ocurre como hacer que cuando el idioma sea diferente a **en** no aparezca el atributo lang, para que no se reitere que el texto se encuentra en español cuando sea el caso, no se si me di a entender XD
