### ISSUE TITLE
El hot-reload no funciona correctamente

### ISSUE THREAD

**Issue by SoyDiego** [cuentoneta/cuentoneta#338]
### ¿Existe un problema similar reportado?

- [X] Es un problema completamente nuevo

### Descripción del problema

Al hacer algún cambio en el proyecto, el hot-reload no funciona. Se queda cargando todo el tiempo.
Al tocar F5 el cambio se visualiza, pero el hot-reload no funciona en ningún momento.

### Pasos para reproducir el problema

1. Levantar el proyecto
2. Hacer un cambio
3. Guardar y visualizar el browser
4. El hot-reload no actualiza/refresca

### Comportamiento esperado

Debería refrescar la página y visualizarse el cambio realizado

### Información adicional / Recursos

- [ESBuild Angular HMR](https://angular.dev/tools/cli/esbuild#hot-module-replacement)

#### Tareas/issues relacionados

- [ ] Transformar AppComponent en standalone #360 
- [ ] Actualizar Nx a última versión 
- [ ] Actualizar Angular y Angular Universal a últimas versiones
- [ ] Evaluar problemas con configuración de proyecto en Nx

**Comment by rolivencia** [comment]
Tal vez la actualización a Angular 16.2 pueda ser un buen momento para ver el asunto del hot reload. Trabajé durante este fin de semana en una MacBook y no tuve problemas en hacer funcionar el hot reload.

**Comment by SoyDiego** [comment]
> Tal vez la actualización a Angular 16.2 pueda ser un buen momento para ver el asunto del hot reload. Trabajé durante este fin de semana en una MacBook y no tuve problemas en hacer funcionar el hot reload.

Más tarde intento actualizar a ver si lo solucionamos Rami 👌

**Comment by rolivencia** [comment]
Hay un issue creado al respecto de Angular 16.2 ya, es este de aquí: #393.

Recordar que hay que hacerlo siempre bajo la órbita de Nx 🖖🏻

**Comment by rolivencia** [comment]
Este problema es un known issue que, al momento, no tiene solución. Voy a marcarlo para reverlo en un hito posterior.

**Comment by rolivencia** [comment]
Para Angular 17.1 y Nx 18.0.0 aún seguimos con el mismo problema.

**Comment by rolivencia** [comment]
Resuelto por #636
