### ISSUE TITLE
Agregar barra de progreso de lectura disponible en v1.0

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#376]

**Comment by rolivencia** [comment]
@ErikGIovani actualicé la PR con los últimos cambios de develop. Restaría sólo transformar algunos estilos que están en `progress-container` y `progress-bar` para usar clases de Tailwind. 

Espero tus indicaciones para proceder luego al merge.

**Comment by ErikGIovani** [comment]
> @ErikGIovani actualicé la PR con los últimos cambios de develop. Restaría sólo transformar algunos estilos que están en `progress-container` y `progress-bar` para usar clases de Tailwind.
> 
> Espero tus indicaciones para proceder luego al merge.

Excelente 🥳, ya hice los cambios de las clases, solo faltaron las de las animaciones, pero tailwind aun no tiene soporte para algunas de esas.

**Comment by rolivencia** [comment]
Excelente. Está creado un nuevo issue (#714) para luego mover el punto de anclaje de la barra de progreso al header.
