### ISSUE TITLE
Correr test de linting al generar builds en Vercel.

### ISSUE THREAD

**Issue by ErikGIovani** [cuentoneta/cuentoneta#384]
### Descripción

Al hacer merge a la rama `develop` se debe de ejecutar una github action que ejecute eslint para hacer linting testing y hacer el deploy a vercel.

### Recursos

- [X] #439
- [x] #718

* [Merge Action](https://github.com/marketplace/actions/branch-merge)
* [Vercel Action](https://vercel.com/guides/how-can-i-use-github-actions-with-vercel)

**Comment by rolivencia** [comment]
@ErikGIovani las Github Actions ya están configuradas para los tests unitarios (ver archivo `.github/workflows/testing.yml`). De manera análoga ya puede agregarse un nuevo archivo para correr el linter.

**Comment by ErikGIovani** [comment]
> @ErikGIovani las Github Actions ya están configuradas para los tests unitarios (ver archivo `.github/workflows/testing.yml`). De manera análoga ya puede agregarse un nuevo archivo para correr el linter, tomando el existente como ejemplo.

Perfecto 🥳, lo estuve revisando ayer cuando mandé pull-request 👌
