### ISSUE TITLE
Generar imágenes para usar en storylist "Textos de Invierno"

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#387]
### Descripción

Se requiere la generación de imágenes vía IA con una temática invernal para incluir en la storylist temática "Textos de Invierno".

### Criterios de aceptación

Generar 5 imágenes invernales, en recuadros, para incluir en la plataforma.

**Comment by llkrakenll** [comment]
tengo 6 img, soy pipe

**Comment by llkrakenll** [comment]
![cabaña](https://github.com/rolivencia/cuentoneta/assets/126592721/5200b814-f219-4c94-9972-22400b07872c)
![camping](https://github.com/rolivencia/cuentoneta/assets/126592721/fc5be4e6-074e-416d-b22e-8dd420c01b56)
![cops1](https://github.com/rolivencia/cuentoneta/assets/126592721/ed88b00c-8bcb-4686-a469-27b4f5ac3469)
![cops2](https://github.com/rolivencia/cuentoneta/assets/126592721/482172c1-000d-4432-b5ee-d6915a63bd48)
![cops3](https://github.com/rolivencia/cuentoneta/assets/126592721/194884f8-784e-42eb-9c0b-643492a59575)
![risco](https://github.com/rolivencia/cuentoneta/assets/126592721/461d71c1-7e6a-4533-9dff-99c706062f91)

**Comment by rolivencia** [comment]
@llkrakenll ¿tenés a mano los prompts que usaste para generar estas imágenes? Podemos ir dándole forma en base a refinar los prompts que tenemos.

Si los guardaste, andá agregándolos en comentarios de este issue.
