### ISSUE TITLE
Agregar responsiveness a tarjetas de storylist

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#413]
### Descripción

Las tarjetas de storylist no se visualizan de manera correcta en dispositivos mobile. Deben adaptarse las tarjetas de storylist para poder visualizarse de manera correcta en viewports de móviles y tablets.

**Comment by omwagh28** [comment]
@rolivencia Assign me this issue

**Comment by rolivencia** [comment]
Marco como bloqueado dado que requerimos los nuevos diseños.
