### ISSUE TITLE
Accesibilidad: Inspeccionar saltos de línea

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#435]
### Descripción

Para cumplir con las directivas de la [WCAG 1.4.12](https://www.w3.org/WAI/WCAG21/Understanding/text-spacing.html), el texto multilíneas de la aplicación debe tener un `line-height` de al menos 1.5. Chequear que se esté cumpliendo la condición para todo el texto de las distintas vistas de la aplicación e implementar correcciones donde sea necesario.

### Criterios de aceptación

Todos los textos multilínea de la aplicación deben tener un `line-height` de 1.5

### Recursos

* https://www.w3.org/WAI/WCAG21/Understanding/text-spacing.html

**Comment by rolivencia** [comment]
Este les puede interesar @Addin @ErikGIovani

**Comment by Addin** [comment]
Me interesa, asignarmelo por favor 😎.
