### ISSUE TITLE
Reemplazar tags usados para estilizar texto

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#436]
### Descripción

Debe reemplazarse el uso de `<strong>` y `<em>` en el cuerpo de texto de la vista story y el cuerpo de texto de las story cards por los tags `<b>` e `<i>`, cuyo significado semántico coincide más con el caso de uso de la aplicación.

### Criterios de aceptación

* Todos los usos de `<strong>` en cuerpos de texto deben ser reemplazados por `<b>`
* Todos los usos de `<em>` en cuerpos de texto deben ser reemplazados por `<i>`

### Recursos

* https://www.w3schools.com/html/html_formatting.asp

**Comment by JimerSamuel** [comment]
I take it

**Comment by rolivencia** [comment]
El último commit conservó los cambios en el package-lock.json pero removió los anteriores. ¿Podemos revertirlo?

En caso que necesites que charlemos sobre el feature, notifícame vía Discord.

**Comment by JimerSamuel** [comment]
Hola Ramio, buenas noches, ya estoy mirando que paso, te notifico cualquier novedad,    En martes, 7 de noviembre de 2023, 17:33:19 GMT-5, Ramiro Olivencia ***@***.***> escribió:  
 
 


El último commit conservó los cambios en el package-lock.json pero removió los anteriores. ¿Podemos revertirlo?

En caso que necesites que charlemos sobre el feature, notifícame vía Discord.
