### ISSUE TITLE
Chequear contrast ratio en colores utilizados 

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#437]
### Descripción

Los colores utilizados para fondos y texto a lo largo de la aplicación deben cumplir con la condición de tener un contrast ratio de 4.5 o mayor. Buscar posibles casos de pares de colores de fondo/elementos que no cumplan con la condición.

### Criterios de aceptación

Todos los pares de colores de fondo/elementos utilizados deben tener un contrast ratio de 4.5 o superior.

### Recursos

* https://developers.google.com/codelabs/devtools-cvd?hl=es-419#0
* https://devtoolstips.org/tips/en/detect-low-color-contrast/
* https://dev.to/domizajac/how-to-use-chrome-devtools-to-find-a-color-fixing-insufficient-color-contrast-ratio-on-your-html-element-546k

**Comment by ErikGIovani** [comment]
> ### Descripción
> Los colores utilizados para fondos y texto a lo largo de la aplicación deben cumplir con la condición de tener un contrast ratio de 4.5 o mayor. Buscar posibles casos de pares de colores de fondo/elementos que no cumplan con la condición.
> 
> ### Criterios de aceptación
> Todos los pares de colores de fondo/elementos utilizados deben tener un contrast ratio de 4.5 o superior.
> 
> ### Recursos
> * https://developers.google.com/codelabs/devtools-cvd?hl=es-419#0
> * https://devtoolstips.org/tips/en/detect-low-color-contrast/
> * https://dev.to/domizajac/how-to-use-chrome-devtools-to-find-a-color-fixing-insufficient-color-contrast-ratio-on-your-html-element-546k

@rolivencia el único elemento que encontré en el home con un contrast ratio menor fue el día, con un contrast ratio de 4.29
![image](https://github.com/cuentoneta/cuentoneta/assets/46170949/58e54c55-c533-40e1-b498-84a206a868ce)

**Comment by ErikGIovani** [comment]
Es el único de todas las paginas

**Comment by ErikGIovani** [comment]
Rectifico, todos los elementos tienen un contrast ratio valido 🎉

**Comment by rolivencia** [comment]
Lo cerramos y movemos a 2.3.3, si es posible.
