### ISSUE TITLE
Poner en funcionamiento Github Actions para correr tests en CI/CD

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#439]
### Descripción

Se requiere poner en funcionamiento una Github Action para correr los tests unitarios a la hora de generar cada Pull Request.

Debe ejecutarse el comando `nx test` como parte de la implementación.

### Recursos

* [How to setup a CI/CD pipeline using Github Actions](https://www.youtube.com/watch?v=JUKZVlIDrtY)
* [Introduction to GitHub Actions](https://learn.microsoft.com/en-us/training/modules/github-actions-automate-tasks/1-introduction)

**Comment by Aborja-dev** [comment]
hola quisiera tomar esta issue por favor

**Comment by rolivencia** [comment]
@Aborja-dev, ¿cómo vas con este asunto? ¿Requieres ayuda de parte de alguien más del equipo?
