### ISSUE TITLE
Reemplazo de estilos redundantes por clases de Tailwind

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#449]
### Descripción

Eliminar estilos redundantes que pueden ser reemplazados por clases de Tailwind. Llevar adelante un chequeo, componente por componente, para abordar el issue.

### Tareas

- [x] #591
- [x] #592
- [x] #593
- [x] #594
- [x] #595
- [x] #596
- [x] #605
- [x] #607
- [x] #608
- [x] #609
- [x] #611
- [x] #598
- [x] #604
- [x] #606
- [x] #601
- [x] #602
- [x] #597
- [x] #599
- [x] #600
- [x] #589
- [x] #603
- [x] #590
- [x] #610

### Cuestiones a considerar
* Reemplazo del uso de las variables `$spacing-` por los spacing de Tailwind 
* Reducir al mínimo posible las clases custom utilizadas en los archivos SCSS

#### Sobre `@apply`:
https://github.com/tailwindlabs/tailwindcss/discussions/5258#discussioncomment-1979394

#### Sobre colores:
https://v2.tailwindcss.com/docs/customizing-colors#custom-colors

#### Sobre opacidad:
https://github.com/adamwathan/tailwind-css-variable-text-opacity-demo

### Recursos

* [Docs Tailwind](https://tailwindcss.com/docs/installation)

**Comment by MiaFate** [comment]
agrego esta info para tratar el issue:


https://github.com/tailwindlabs/tailwindcss/discussions/5258#discussioncomment-1979394

**Comment by rolivencia** [comment]
Cierro issue ya que todos los issues derivados han sido resueltos.
