### ISSUE TITLE
Agregar label de good first issue y agregar a La Cuentoneta a la pagina de For Good First Issue

### ISSUE THREAD

**Issue by ErikGIovani** [cuentoneta/cuentoneta#473]
### Descripción

Agregar label **good first issue** para que aparezcan los issues con ese label en la pagina de contribute de La Cuentoneta y agregarlo a los issues con la label **buen primer issue**, también agregar La Cuentoneta a la pagina de  For Good First Issue de Github.

### Criterios de aceptación

Al entrar a la pagina de contribute que aparece en los recursos de este issue deben de aparecer los buenos primeros issues para hacer.

### Recursos

* [For Good First Issue](https://forgoodfirstissue.github.com/)
* [Contribute](https://github.com/cuentoneta/cuentoneta/contribute)

**Comment by rolivencia** [comment]
Agregada solicitud para transformar el proyecto en un Digital Public Good.

![image](https://github.com/cuentoneta/cuentoneta/assets/32349705/5b7bd787-fbd6-4720-b26a-8fd309ffc297)

Agregada solicitud para que aparezca el proyecto en For Good First Issue.

https://github.com/github/forgoodfirstissue/issues/99

**Comment by rolivencia** [comment]
Cambiado el nombre del tag para `good first issue`. Ahora los issues aparecen en https://github.com/cuentoneta/cuentoneta/contribute
