### ISSUE TITLE
Agregar a documentación la inclusión del proyecto en For Good First Issue

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#502]
### Descripción

El proyecto La Cuentoneta se encuentra ahora agregado a la iniciativa _For Good First Issue_ (https://forgoodfirstissue.github.com/). Debe incluirse este detalle en la documentación principal del proyecto.

### Recursos

* Issue en For Good First Issue: https://github.com/github/forgoodfirstissue/issues/99#event-11284424308

**Comment by ErikGIovani** [comment]
> Quisiera tomar esta issue

Este issue ya fue resuelto el 2 Junio 👌
