### ISSUE TITLE
Agregar Vercel Speed Insights al tooling de la aplicación

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#553]
### Descripción

Se requiere agregar Vercel Speed Insights para tener trazabilidad y evaluación de métricas relacionadas a la velocidad de carga y optimización de la página.

Conjuntamente con Lighthouse, puede servir como herramienta para saber qué ajustes son necesarios en la aplicación para obtener una mejor performances y una mejor experiencia de usuario.

### Recursos

Información sobre la herramienta y pasos para su instalación: https://vercel.com/docs/speed-insights

**Comment by Addin** [comment]
Me gustaría tomar este issue, leyendo el [Vercel Speed Insights Quickstart](https://vercel.com/docs/speed-insights/quickstart) indica que hay que activarlo en el dashboard del proyecto en Vercel.
Puedo hacer los cambios en el código y luego se comprueba que se visualice bien la información en el dashboard.

**Comment by rolivencia** [comment]
Asignado Rome. Por cualquier consulta escribinos al canal en Discord. CC @ErikGIovani

**Comment by rolivencia** [comment]
Supongo que el lugar predilecto para poner a funcionar esta herramienta es en `app.component.ts`, como ya hemos hecho para Vercel Analytics @Addin
