### ISSUE TITLE
Corregir warnings de compilación

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#556]
### ¿Existe un problema similar reportado?

- [ ] Existe un problema similar
- [X] Es un problema completamente nuevo

### Descripción del problema

Existe un número de warnings sin resolver que el compilador reporta al correr el proyecto localmente o generar un build.

### Pasos para reproducir el problema

1. Correr la aplicación en build local.
2. Chequear warnings que aparecen en la consola.

**Comment by Addin** [comment]
Hola 😊.
Por favor asignarme este issue.

**Comment by ErikGIovani** [comment]
> Hola 😊. Por favor asignarme este issue.

Asignado 👍
