### ISSUE TITLE
Remover uno de los links del home repetidos en el header

### ISSUE THREAD

**Issue by ErikGIovani** [cuentoneta/cuentoneta#562]
### ¿Existe un problema similar reportado?

- [ ] Existe un problema similar
- [X] Es un problema completamente nuevo

### Descripción del problema

Para no causar molestias a las personas que hacen uso del lector de pantalla es necesario remover el link del logo para evitar que al navegar por la pagina el lector de pantalla lea dos veces la url del home, ya que se encuentra también ubicada la misma url en el elemento siguiente.

### Pasos para reproducir el problema

1. Esperar al refactor de el header que se encuentra en el nuevo diseño.
2. Remover el link del logo manteniendo los mismo estilos del diseño.

**Comment by rolivencia** [comment]
Deberíamos borrar el link de "Inicio", dejando la navegación al home en manos del elemento ícono + título de la izquierda.

**Comment by ErikGIovani** [comment]
> Deberíamos borrar el link de "Inicio", dejando la navegación al home en manos del elemento ícono + título de la izquierda.

Si gustas mejor solo ocultamos el segundo link solo para los lectores de pantalla, con el atributo aria-hidden="true" 👌

Así evitamos hacer cambios en el diseño

**Comment by ErikGIovani** [comment]
> Deberíamos borrar el link de "Inicio", dejando la navegación al home en manos del elemento ícono + título de la izquierda.

Ya agregué los cambios, le puse un aria-hidden="true" solo cuando el navLink.label sea igual a "Inicio" para que el lector de pantalla no lo lea y también le puse un tabindex="-1" para que no sea navegable el link de Inicio con el tabulador, el tabindex="0" es para que siga el orden normal de tabulación del elemento 🥳

**Comment by rolivencia** [comment]
Excelente Erik, me parece una mejor solución esta que la de sólo quitar la navegación. Luego seguramente revisitaremos estas características al agregar más opciones de navegación en el header.

**Comment by ErikGIovani** [comment]
> Excelente Erik, me parece una mejor solución esta que la de sólo quitar la navegación. Luego seguramente revisitaremos estas características al agregar más opciones de navegación en el header.

Perfecto 👍
