### ISSUE TITLE
Cambiar usos de *ngFor por @for en about.component.html

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#576]

**Comment by Aborja-dev** [comment]
me gustaria tomar este issue

**Comment by ErikGIovani** [comment]
> me gustaria tomar este issue

Hola @Aborja-dev 👋, si tienes dudas con el issue no dudes en preguntar 👍

**Comment by Aborja-dev** [comment]
hola ya esta el issue resuelto

**Comment by rolivencia** [comment]
Recuerda enviar el Pull Request desde tu fork hacia el repositorio original para que podamos evaluar los cambios.
