### ISSUE TITLE
Optimizar imágenes usadas en StorylistCardComponent

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#582]
### Descripción

Vercel Speed Insights reporta posibles mejoras en performance relacionadas a las imágenes visibles en el home. Se debe trabajar en optimizar la carga de estas imágenes.

Posibles estrategias a evaluar:
- Uso de `ngOptimizedImage`
- Uso de bloque `@defer`
- Cambio de formato de imágenes a WebP, ADIF, etc.
- Chequear recomendaciones de Lighthouse

### Criterios de aceptación

[A DESARROLLAR]

**Comment by Addin** [comment]
@ErikGIovani ¿Vos estabas trabajando en este issue o está libre para tomar?

**Comment by ErikGIovani** [comment]
> @ErikGIovani ¿Vos estabas trabajando en este issue o está libre para tomar?

Se encuentra libre 👍

**Comment by Addin** [comment]
Genial, me lo asignas por favor.
