### ISSUE TITLE
Agregar visualización de íconos en StoryCardComponent para stories con spaces de X

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#585]
### Descripción

De manera similar a como sucede con las stories que poseen asociados videos de YouTube, se requiere poder visualizar previamente a la lectura de una story (y al acceso de la vista en la ruta `/story`) si es que la misma posee asociado un recurso multimedia de tipo `spaceRecording`.

Para lograrlo, debe implementarse la visualización de un ícono distintivo en los componentes `StoryComponent` y `StoryNavigationBarComponent` que permita identificar a aquellas historias con este tipo de recursos y posea asociado el logo de la red social X.

### Criterios de aceptación

Las stories que poseen asociados objetos de tipo `spaceRecording` en la propiedad de tipo array `media` deben visualizar, de manera visualmente similar a la captura de aquí abajo, un logo de la red social X.

![image](https://github.com/cuentoneta/cuentoneta/assets/32349705/a35df032-dbad-489d-9bda-4a171c0ba004)

### Recursos

* La storylist "Desde el Sótano de la Casa de la Calle Garay" posee historias con este tipo de recursos asociados.
* El logo de X está disponible en los assets del proyecto, con lo que puede ser reutilizado para esta tarea.
* Para determinar si es que una Story debe visualizar en la Navbar o en una StoryCard el logo de X, debe chequearse si la entidad Story en cuestión posee dentro de su propiedad `media` un objeto de tipo `spaceRecording`. Puede tomarse como referencia la validación que se realiza alrededor de la línea 63 de `story.component.html` para determinar si se muestra o no el banner asociado a spaces de X.

**Comment by Addin** [comment]
Hola Rami, me gustaría trabajar en este issue, ¿En qué te puedo ayudar para refinar el ticket?

**Comment by rolivencia** [comment]
Agrego en breve el detalle para habilitar que pueda trabajarse. Se requiere hacer algo similar a lo ya implementado para las stories que tienen asociados como recursos videos en YouTube.

**Comment by rolivencia** [comment]
Actualizada la descripción @Addin. Te lo dejo asignado para trabajar y quedo disponible para consultas.
