### ISSUE TITLE
Problema para visualizar StoryCardComponent en Storybook

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#620]
### ¿Existe un problema similar reportado?

- [ ] Existe un problema similar
- [X] Es un problema completamente nuevo

### Descripción del problema

La inclusión del componente `YouTubePlayerComponent` causó que las stories de Storybook para `StoryCardComponent` no sean accesibles.

### Pasos para reproducir el problema

1. Ejecutar Storybook localmente.
2. Acceder a alguna de las stories de `StoryCardComponent`.
3. Chequear errores en pantalla asociados a `YouTubePlayerComponent`.

### Comportamiento esperado

Debe poder accederse normalmente a estas stories.

### Capturas de pantalla

![image](https://github.com/cuentoneta/cuentoneta/assets/32349705/a8ec4961-daaf-4070-9239-3c721565c896)

### Información adicional / Recursos

El problema está causado por la falta de imports en `story-card.component.stories.ts` del nuevo componente `YouTubePlayerComponent`. Su agregado debería solucionar el problema.

**Comment by ErikGIovani** [comment]
@rolivencia creo que no se te instaló bien el paquete @angular/youtube-player , acabo de probar y no me aparece ese error

![image](https://github.com/cuentoneta/cuentoneta/assets/46170949/63ba3703-4838-40a5-bd04-271bf0f62717)

**Comment by rolivencia** [comment]
Vuelvo a intentar y te notifico 👍🏻

**Comment by rolivencia** [comment]
Cierro el issue, al parecer era un problema local entre mis branches.
