### ISSUE TITLE
Cambiar el uso de queryParams por params en las storylist

### ISSUE THREAD

**Issue by ErikGIovani** [cuentoneta/cuentoneta#621]
### Descripción

A fin de poder hacer prerender de todas las storylists incluidas en la plataforma se piensa en la posibilidad de cambiar las rutas de las storylists para que usen `params` en vez de `queryParams`.

### Criterios de aceptación

Los queryParams deben de ser sustituidos por params.

### Recursos

* [Router reference](https://angular.dev/guide/routing/router-reference)
* [Param como Input](https://angular.dev/guide/routing/common-router-tasks#add-an-input-to-the-component)

**Comment by rolivencia** [comment]
Aparentemente el problema estaba causado por un error totalmente ajeno al router, pero que a nivel de SSR puede provocar este tipo de problemas. Vi esta información en un post de StackOverflow e hice el chequeo de arreglar un error relacionado a ngSrc, lo cual casi de manera _mágica_ solucionó el problema con las rutas de múltiples parámetros en SSR.
