### ISSUE TITLE
Agregar logo de Tertulia Literaria en README.md

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#625]
### Descripción

Deben agregarse los logos de las comunidades que colaborarán con La Cuentoneta en la organización del III Certamen de Literatura.

### Recursos

![Taller-de-Escritura (1)](https://github.com/cuentoneta/cuentoneta/assets/32349705/6d7aa272-e61b-409d-9b68-8a805e8c98a6)
![fotoefectos com_](https://github.com/cuentoneta/cuentoneta/assets/32349705/ae6eef09-895a-4282-9c6b-63ae33db814e)
![TL_12](https://github.com/cuentoneta/cuentoneta/assets/32349705/7ca8a3d3-ed76-4785-a6ef-f3f7498b94c3)

**Comment by Addin** [comment]
Hola, me gustaría tomar este issue, en los recursos aparece dos veces el logo de "taller de escritura creativa", ¿tal vez te equivocaste y uno tendría que ser el logo de "Tertulia Literaria"?

**Comment by rolivencia** [comment]
Falta el de Tertulia Literaria pues aún deben enviarlo en formato SVG. Marco el issue como bloqueado.

**Comment by rolivencia** [comment]
Agregado logo de TL a README.md, con una descripción de la comunidad. Procedo a cerrar el issue.
