### ISSUE TITLE
Completar formulario para agregar a La Cuentoneta al registro de Digital Public Goods

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#626]
### Descripción

Completar el registro del proyecto en el registro de Digital Public Goods, a fin de ganar visibilidad y poder certificar el valor archivístico y cultural del proyecto.

**Comment by Addin** [comment]
Me gustaría trabajar en este, ¿cuál es el formulario al que haces referencia?

**Comment by rolivencia** [comment]
Esta es una gestión que estoy llevando adelante con ese organismo. Me olvidé de autoasignarme el issue.

**Comment by rolivencia** [comment]
La gestión ya fue completada y estamos esperando respuesta desde el organismo. Doy por cerrado el issue.
