### ISSUE TITLE
Cálculo de posición del Tooltip para textos multi-línea

### ISSUE THREAD

**Issue by MiguelGalp** [cuentoneta/cuentoneta#698]
### ¿Existe un problema similar reportado?

- [ ] Existe un problema similar
- [X] Es un problema completamente nuevo

### Descripción del problema

El Tooltip se "pisa" sobre los badges de las categorías (por ej. "Curaduría" o "Antología") cuando su texto es multi-línea

### Pasos para reproducir el problema

1. Posar mouse sobre badge "Antología" de la tarjeta "Cuentos de terror". El largo del texto del Tooltip hace que el texto cree una segunda línea, lo que modifica la posición del Tooltip haciéndolo "pisar" sobre el badge. Ver imagen abajo.

### Comportamiento esperado

El Tooltip debiera estar posicionado de manera tal de verse completo y sin pisar el badge

### Capturas de pantalla

![Screenshot 2024-04-11 at 12 27 45](https://github.com/cuentoneta/cuentoneta/assets/85765429/b838ab73-5b29-472b-abd1-110e5c2659db)

**Comment by franciscohanna92** [comment]
@MiguelGalp voy a trabajar en este.

Que opinas de usar [floating-ui](https://floating-ui.com/) (anteriormente conocida com popper.js) para el computo de posición del tooltip/arrow? No es una tarea trivial hacerlo y esa lib provee una lindas abstracciones para lograrlo.

**Comment by franciscohanna92** [comment]
La tomé!
