### ISSUE TITLE
Preparar ejecución de Github Actions funcionales

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#721]
### Descripción
Se requiere poner en funcionamiento práctico a las actions orientadas a correr el linter y la batería de unit tests en el pipeline de CI/CD. Se requiere resolver las tareas listadas en orden para proceder, luego, a bloquear el merge de PRs en caso de que no se cumpla con las restricciones.

El completar este issue es condición necesaria para poder llevar adelante luego la resolución de #739.

## Tareas
- [x] #738
- [x] Activar la restricción a la hora de hacer merge si el linter arroja errores al correr.
- [x] #915
- [x] Activar la restricción a la hora de hacer merge si algún test unitario arroja errores al correr.

**Comment by ErikGIovani** [comment]
@rolivencia estuve viendo lo de el branding de las actions y solo funciona cuando se publica una action en el marketplace de las github actions.

https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#branding

**Comment by rolivencia** [comment]
Completados todos los issues derivados y tareas incluidas en este issue. Procedo a darle cierre. cc @ErikGIovani
