### ISSUE TITLE
Cambiar ícono utilizado para recursos multimedia de tipo audioRecording

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#723]
## Tareas
- [ ] Agregar el nuevo ícono del SVG adjunto a la carpeta `assets/svg`, con el nombre `waveform.svg`
- [ ] Cambiar el atributo `src` de la línea 42 del template de `StoryNavigationBarComponent` por la ruta del nuevo ícono
- [ ] Cambiar el atributo `src` de la línea 51 del template de `StoryCardComponent` por la ruta del nuevo ícono
- [ ] Eliminar ícono anterior, `speaker.svg`, de la base de código

### Recursos

SVG del nuevo ícono:
![waveform-circle-fill](https://github.com/cuentoneta/cuentoneta/assets/32349705/78f82050-a85c-40dc-8140-6d7bd6c81343)

**Comment by Addin** [comment]
Me asignan este issue por favor.

**Comment by rolivencia** [comment]
Asignado @Addin. Si lo trabajás antes del finde lo movemos a la 2.4.1 para pasarlo a producción cuanto antes 😄

**Comment by Addin** [comment]
Sin problemas, sale hoy 👍.
