### ISSUE TITLE
Corregir problema con ejecución de `nx lint`.

### ISSUE THREAD

**Issue by ErikGIovani** [cuentoneta/cuentoneta#738]
### Issues derivados:

A fin de marcar este issue como resuelto deben marcarse como resueltos todos los siguientes issues de la lista, los cuales involucran la resolución de errores y warnings reportados por eslint:
- [x] #741
- [x] #814
- [x] #742
- [x] #813
- [x] #806

- [x] #805
- [x] #812
- [x] #808
- [x] #804
- [x] #810
- [x] #803
- [x] #807
- [x] #809
- [x] #811
- [x] #740

### Tareas a encarar al término
- [x] #888
- [x] #907

**Comment by rolivencia** [comment]
Agregados todos los issues derivados siguiendo la línea planteada inicialmente @ErikGIovani

**Comment by ErikGIovani** [comment]
> Agregados todos los issues derivados siguiendo la línea planteada inicialmente @ErikGIovani

Excelente 🥳

**Comment by rolivencia** [comment]
Todos los issues derivados han sido completados. Procedo a cerrar y dar por completado el epic.

**Comment by Demon-Sheriff** [comment]
> > Todos los issues derivados han sido completados. Procedo a cerrar y dar por completado el epic.
> > Buen trabajo @ErikGIovani @Demon-Sheriff @luz-ojeda.
> 
> We did it Reddit ⸜(｡˃ ᵕ ˂ )⸝♡
Yes !  🙌😊
