### ISSUE TITLE
Corregir los errores y warnings del archivo functions.ts

### ISSUE THREAD

**Issue by ErikGIovani** [cuentoneta/cuentoneta#740]
## Pasos para resolver el problema:
- Ir al archivo en la ruta **src/api/_utils/functions.ts**
- Resolver los errors y warnings que marca el linter en ese archivo
- Aprovechar para llevar adelante refactor del método `mapResources()` y agregar un early return en reemplazo del nullish coalescing operator de la línea 61.

### Linter log:

- 19:42  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- 33:50  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- 68:44  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- 70:57  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- 73:27  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- 74:24  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
- 98:34  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

**Comment by franciscohanna92** [comment]
Ppara poder resolver algunos de esos errores sería necesario tipar los resultados de las queries de Sanity. Se podrían tipar a manualmente, pero lo idea sería poder generar las interfaces de las queries de manera automática. Encontré esto por si alguien con mas experiencia en Sanity lo quiere revisar y ver si es viable: https://www.sanity.io/learn/course/typescripted-content/generating-type-for-groq-query-results.

**Comment by franciscohanna92** [comment]
@luz-ojeda Yo diria que si. Corrigiendo los typings de las respuestas de de Sanity, luego es solo cuestión de user esos types para las funciones en `functions.ts`

**Comment by luz-ojeda** [comment]
> @luz-ojeda Yo diria que si. Corrigiendo los typings de las respuestas de de Sanity, luego es solo cuestión de user esos types para las funciones en `functions.ts`

Agarro ambas si les parece ok

**Comment by Addin** [comment]
Asignado el issue a @luz-ojeda.
