### ISSUE TITLE
Corregir los errores y warnings del archivo story.service.ts

### ISSUE THREAD

**Issue by ErikGIovani** [cuentoneta/cuentoneta#741]
## Descripción del problema:

Resolver los errors y warning del archivo **story.service.ts**

## Pasos para resolver el problema:
- Ir al archivo en la ruta **src/api/story.service.ts**
- Resolver los errors y warnings que marca el linter en ese archivo

### Linter log:
35:25  warning  'author' is assigned a value but never used  @typescript-eslint/no-unused-vars

**Comment by luz-ojeda** [comment]
La tomo

**Comment by luz-ojeda** [comment]
Parece que se resolvieron en algún otro commit, si alguno quiere hacer un double check así la cerramos

**Comment by rolivencia** [comment]
Confirmo, debe ser algún cambio que introduje en las PRs para perfil de autor. Procedo a cerrarlo.
