### ISSUE TITLE
Cambiar manejo en render de skeletons

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#750]
### Descripción

Transformar la actual lógica para render de skeletons, simplificando y abstrayendo la estructura de los skeletons de la estructura de los componentes de contenido.

### Criterios de aceptación

- Remover la lógica de clonación de la estructura de una storylist para la generación de los skeletons.
- Implementar lógica que genere la visualización de los skeletons de forma parametrizada mediante un algoritmo, manejando una generación parcialmente aleatoria de las tarjetas visibles.

### Recursos
- Relacionado con #960

**Comment by wilcoxmarin** [comment]
Quisiera trabajar en issues

**Comment by ErikGIovani** [comment]
> Quisiera trabajar en issues

Asignado 👍

**Comment by rolivencia** [comment]
@wilcoxmarin este issue tiene una complejidad y falta de detalle que hará complejo el abordaje. Se encuentra sin el nivel de detalle requerido para comenzar a trabajar dado que no está asignado a ningún hito futuro aún. Te recomiendo comenzar por otro issue más sencillo para ir conociendo el proyecto.

Procedo a taggearlo como complejo @ErikGIovani.

**Comment by wilcoxmarin** [comment]
@rolivencia  Okay entiendo, vi otro issue #677 que dicen por ese puede empezar?

**Comment by rolivencia** [comment]
Cualquiera dentro del hito 2.4.3 está dentro de lo prioritario, aunque sólo #815 está sin asignar. Si te interesa puedes comenzar con ese. Comenta en el issue y te lo asignamos.

En breve comenzaremos a planificar el hito de la versión 2.4.4, en el que incluiremos al #677.

**Comment by wilcoxmarin** [comment]
En el #815 veo un comentario el no asignado el issue ? y si no esta lo esta pues me asignas a mi

**Comment by rolivencia** [comment]
Procedo a cerrar el issue, dado que ya fue abordado.
