### ISSUE TITLE
Corregir los errores y warnings del archivo navigable-story-teaser.component.ts

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#803]
## Pasos para resolver el problema:
- Ir al archivo en la ruta **src/app/components/navigable-story-teaser/navigable-story-teaser.component.ts**
- Resolver los errors y warnings que marca el linter en ese archivo

### Linter log:

- 3:21  warning  'StoryPreview' is defined but never used  @typescript-eslint/no-unused-vars

**Comment by harsh-791** [comment]
Hey, I would like to work on this issue. @rolivencia 
Would it work if the remove StoryPreview as its being imported but never used.
