### ISSUE TITLE
Corregir los errores y warnings del archivo footer.component.ts

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#804]
## Pasos para resolver el problema:
- Ir al archivo en la ruta **src/app/components/footer/footer.component.ts**
- Resolver los errors y warnings que marca el linter en ese archivo

### Linter log:

- 133:23  warning  'event' is defined but never used  @typescript-eslint/no-unused-vars

**Comment by rushil-118** [comment]
Hey, I would like to work on this issue.
As the event is not used would it be fine to remove it?
Currently, it is given as parameter to `onMenuTogglerClicked` function, but we're just toggling  displaymenu in the function.
![Screenshot from 2024-07-16 21-20-20](https://github.com/user-attachments/assets/dc12479b-db86-403d-800b-5e5280b36905)

**Comment by rolivencia** [comment]
> Hey, I would like to work on this issue. As the event is not used would it be fine to remove it? Currently, it is given as parameter to `onMenuTogglerClicked` function, but we're just toggling displaymenu in the function. ![Screenshot from 2024-07-16 21-20-20](https://private-user-images.githubusercontent.com/144247815/349185182-dc12479b-db86-403d-800b-5e5280b36905.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNDY1NTQsIm5iZiI6MTcyMTE0NjI1NCwicGF0aCI6Ii8xNDQyNDc4MTUvMzQ5MTg1MTgyLWRjMTI0NzliLWRiODYtNDAzZC04MDBiLTVlNTI4MGIzNjkwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQxNjEwNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mM2ZlNTM4YWI0MWI2NDMwNmI0ZjU0ZjRlZGRlZmM3NjFlYWIwYzAwYTE5NGZkZWFkYTdiNzdmNGJlMzdkOTNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.e1nbjabklffM0dOIYryIOQc_XHDkhIiFhdAdmPYSozQ)

Yes, we're good with removing the `event` parameter from the `onMenuTogglerClicked` method. Please check the template of this component, since you'll need to delete the `$event` argument that's used there.

I've already assigned you the issue.

**Comment by rushil-118** [comment]
Yes, will do that
Also, there is a similar issue in the header.component file, would it be fine if I solve that too
