### ISSUE TITLE
Corregir los errores y warnings del archivo portable-text-parser.component.stories.ts

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#807]
## Pasos para resolver el problema:
- Ir al archivo en la ruta **src/app/components/portable-text-parser/portable-text-parser.component.stories.ts**
- Resolver los errors y warnings que marca el linter en ese archivo

### Linter log:

- 9:6  warning  'Story' is defined but never used  @typescript-eslint/no-unused-vars

**Comment by harsh-791** [comment]
Hey, I would like to work on this issue. @rolivencia 
Would it work if the remove Story as its being imported but never used.
