### ISSUE TITLE
Corregir los errores y warnings del archivo share-content.component.ts

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#808]
## Pasos para resolver el problema:
- Ir al archivo en la ruta **src/app/components/share-content/share-content.component.ts**
- Resolver los errors y warnings que marca el linter en ese archivo

### Linter log:

- 81:58  warning  'message' is defined but never used  @typescript-eslint/no-unused-vars

**Comment by rolivencia** [comment]
Since there's sharing platforms that doesn't allow us to write a specific message beforehand, like `FacebookPlatform` class, what we need to do is to set the `message` field as optional in the `SharingPlatform` interface.

`generateSharingUrl(appRoute: string, urlParams: string, message: string): string;` in line 71 of `share-content.component.ts` should be set to `generateSharingUrl(appRoute: string, urlParams: string, message?: string): string;`

That'll allow you to skip the `message` parameter in the `generateSharingUrl()` implementation for `FacebookPlatform` class.

**Comment by rushil-118** [comment]
Thank you for the help, so is this good enough?
![Screenshot from 2024-07-16 18-56-18](https://github.com/user-attachments/assets/2aa9d0eb-2f9b-4f89-b57e-a7a18ffc352f)

**Comment by rolivencia** [comment]
> Thank you for the help, so is this good enough? ![Screenshot from 2024-07-16 18-56-18](https://private-user-images.githubusercontent.com/144247815/349102189-2aa9d0eb-2f9b-4f89-b57e-a7a18ffc352f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMzY3MjIsIm5iZiI6MTcyMTEzNjQyMiwicGF0aCI6Ii8xNDQyNDc4MTUvMzQ5MTAyMTg5LTJhYTlkMGViLTJmOWItNGY4OS1iNTdlLWE3YTE4ZmZjMzUyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQxMzI3MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMWQ0YTMxMTIzZjRhMWViY2RjMjA2ODYxNmQ2M2I2M2U4NTQ0MmFlZTM5MDcyMThlYmU3Y2ViMjhmNzVhMzkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FYqOh8BrDCsci9ga5ugv5nm-_PrwmWM5O_uWelwY3Eg)

No, it's not. You should proceed with the removal of the `message` parameter in the line 82 declaration for the `generateSharingUrl` method. Please check my previous comment.

**Comment by rushil-118** [comment]
![Screenshot from 2024-07-16 19-20-15](https://github.com/user-attachments/assets/15a79ded-d323-4f21-9d33-fc46dec840a8)
did you mean this?

**Comment by rolivencia** [comment]
> ![Screenshot from 2024-07-16 19-20-15](https://private-user-images.githubusercontent.com/144247815/349110912-15a79ded-d323-4f21-9d33-fc46dec840a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMzgyMzQsIm5iZiI6MTcyMTEzNzkzNCwicGF0aCI6Ii8xNDQyNDc4MTUvMzQ5MTEwOTEyLTE1YTc5ZGVkLWQzMjMtNGYyMS05ZDMzLWZjNDZkZWM4NDBhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQxMzUyMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yM2M4MjA0YjJiY2JhN2FlYTE1MjhhZGRlNTE0YjdlY2ZhMGZkZTg4MWQzYjVlMmY1MzRkY2I4YTFjYzJlMGE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vacfElOeNPPyvVaKBVxY9dLP7yJM5NUTWv1bc_a1WW0) did you mean this?

Yes, that's it. You can submit a PR with those changes.

**Comment by rushil-118** [comment]
Thanks for the help.
