### ISSUE TITLE
Corregir los errores y warnings del archivo story-card-content.component.ts

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#809]
## Pasos para resolver el problema:
- Ir al archivo en la ruta **src/app/components/story-card-content/story-card-content.component.ts**
- Resolver los errors y warnings que marca el linter en ese archivo

### Linter log:
- 1:31  warning  'effect' is defined but never used  @typescript-eslint/no-unused-vars

**Comment by harsh-791** [comment]
Hey, I would like to work on this issue. @rolivencia 
Would it work if the remove effect as its being imported but never used.
