### ISSUE TITLE
Corregir los errores y warnings del archivo storylist-card-deck.component.ts

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#811]
## Pasos para resolver el problema:
- Ir al archivo en la ruta **src/app/components/storylist-card-deck/storylist-card-deck.component.ts**
- Resolver los errors y warnings que marca el linter en ese archivo

### Linter log:

- 2:72  warning  'OnInit' is defined but never used  @typescript-eslint/no-unused-vars
- 50:65  warning  Forbidden non-null assertion        @typescript-eslint/no-non-null-assertion
- 59:32  warning  Forbidden non-null assertion        @typescript-eslint/no-non-null-assertion
- 63:26  warning  Forbidden non-null assertion        @typescript-eslint/no-non-null-assertion
- 78:32  warning  Forbidden non-null assertion        @typescript-eslint/no-non-null-assertion
- 82:27  warning  Forbidden non-null assertion        @typescript-eslint/no-non-null-assertion

**Comment by harsh-791** [comment]
Hey, I would like to work on this issue. @rolivencia 
Would it work if the remove OnInit as its being imported but never used.

**Comment by harsh-791** [comment]
Hey, I would like to work on this issue. @rolivencia
Would it work if the remove OnInit as its being imported but never used.

**Comment by rolivencia** [comment]
I've assigned it to you. This one is harder to fix than the others since it involves the use of the non null assertion operators, which may trigger some typing errors when removed.

**Comment by rolivencia** [comment]
Any news in regards to this issue @harsh-791?

**Comment by rolivencia** [comment]
Me assigno el issue dado que no tuvimos noticias del dev involucrado previamente.
