### ISSUE TITLE
Migrar inputs de `StorylistCardDeckComponent` a signals.

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#815]

**Comment by poojatalele** [comment]
I would like to work on this, kindly assign.

**Comment by wilcoxmarin** [comment]
Este issue esta disponible para que me loa asigne ?

**Comment by ErikGIovani** [comment]
> Este issue esta disponible para que me loa asigne ?

Listo 👌

**Comment by rolivencia** [comment]
@wilcoxmarin: no olvides de notificarnos si requieres cualquier tipo de asistencia para la resolución del issue.
