### ISSUE TITLE
Migrar inputs de `BioSummaryCardComponent` a signals.

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#817]

**Comment by poojatalele** [comment]
I would like to work on this issue, kindly assign.

**Comment by Dipti0704** [comment]
I would like to work on this issue kindly assign this to me.

**Comment by rolivencia** [comment]
I'll assign this one to @poojatalele. Do you have any news regarding #820 @Dipti0704?

**Comment by poojatalele** [comment]
Will start working on this one. @rolivencia

**Comment by poojatalele** [comment]
Heyy!! @rolivencia Sorry for being inactive from past few days...Would like to contribute more. Is there any other good first issue open which I can work on?
