### ISSUE TITLE
Migrar inputs de `StoryCardSkeleton` a signals.

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#820]

**Comment by Dipti0704** [comment]
I would like to work on this issue , kindly assign it.

**Comment by rolivencia** [comment]
I'll assign this one to @Dipti0704 while you work on the others @poojatalele. 

Guys, I'm also curious on how you discovered the project. Can you point me at how you reached us?

**Comment by rolivencia** [comment]
Any news on this issue @Dipti0704? Do you need any help or guidance?

**Comment by Dipti0704** [comment]
No issues sir.
I will raise the PR by tomorrow.

**Comment by rolivencia** [comment]
I'm taking back this issue.
