### ISSUE TITLE
Agregar tipado en función `fetchStorylist`

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#837]
### Descripción
Se requiere tipar mediante Sanity TypeGen los resultados del fetch del cliente de Sanity definido en el método `fetchStorylist` del archivo `api/storylist.service.ts`.

### Tareas

- [x] Definir consulta literal en GROQ utilizando el prefijo `groq` en el archivo `storylist.query.ts`, en reemplazo de la query interpolada existente en `storylist.service.ts`.
- [x] Generar tipado para la consulta utilizando Sanity TypeGen.
- [x] Asignar tipo generado al resultado de la operación `client.fetch`
- [x] Renombrar función `fetchStorylist` a `fetchBySlug`.
- [x] Mover archivos `storylist.service.ts`, `storylist.controller.ts` y `storylist.query.ts` a un nuevo directorio `api/storylist` (tarea también definida en #836)
- [x] Reemplazar tipo `any` en la función `mapStorylist` de `functions.ts` con el tipo resultante de la query.
- [x] En la PR correspondiente al presente issue ligar #740 como segundo issue relacionado. Verificar, al completar la tarea anterior, que el linter no arroja warnings.

**Comment by poojatalele** [comment]
I would like to work on this, kindly assign

**Comment by rolivencia** [comment]
Just assigned it. You can give it a shot.

For guidance check on the already closed PRs which are children of #697.

**Comment by poojatalele** [comment]
This issue has not been assigned to me yet.

**Comment by Addin** [comment]
> This issue has not been assigned to me yet.

Already assigned it to you.

**Comment by rolivencia** [comment]
@poojatalele: @luz-ojeda will handle this issue, so don't worry about it. Can you check on the available Good First Issue to familiarize yourself with the codebase working on a lower-complexity task?

https://github.com/cuentoneta/cuentoneta/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

**Comment by poojatalele** [comment]
okayy!! Thankyou :)
