### ISSUE TITLE
Asignar nivel de rigurosidad `error` para la regla de ESLint `@typescript-eslint/no-explicit-any`

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#888]
# Descripción
Agregar la regla `@typescript-eslint/no-explicit-any` con un valor de rigurosidad `error` en el archivo `.eslintrc.json`

Este issue se encuentra bloqueado a la espera de dar como completados todos los issues de #738 y realizar una auditoría de tipos en el proyecto.

**Comment by Demon-Sheriff** [comment]
I would like to work on this issue.

**Comment by rolivencia** [comment]
@Demon-Sheriff the issue is blocked, since we're waiting for the completion of #738 to work on it.

**Comment by rolivencia** [comment]
@Demon-Sheriff: All the previous steps in #738 are completed now. Please take a look to the #905 PR for further instructions on how to proceed.
