### ISSUE TITLE
Solucionar problemas en tests de `HeaderComponent`

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#889]
### Tareas
- [ ] Agregar el valor del return de la función `setup` directamente como valor de la constante `view` sin usar la función setup.
- [ ] Usar `toBeInTheDocument` en lugar de `toBeTruthy`.
- [ ] Cambiar de `expect(screen.getByRole('link', { name: 'Inicio' })).toHaveProperty('href', expect.stringMatching(/home/));` y `xpect(screen.getByRole('link', { name: 'Nosotros' })).toHaveProperty('href', expect.stringMatching(/about/));` a `expect(screen.getByText(/Inicio/)).toHaveProperty('href', expect.stringMatching(/home/));` y `expect(screen.getByText(/Nosotros/)).toHaveProperty('href', expect.stringMatching(/about/));`.
- [ ] Cambiar la definición de la función `xdescribe` en `describe` antes de crear la pull request vinculada a este issue.

### Recursos
- Revisar otros ejemplos de tests funcionales para tomar como referencia.
- Recordar cambiar `xdescribe` por `describe` para poder correr los tests definidos en `header.component.spec.ts`. Chequear #739 para una descripción más detallada al respecto.
- [Uso de Angular Testing Library](https://testing-library.com/docs/angular-testing-library/examples).

**Comment by omwagh28** [comment]
@rolivencia Assign me this issue
