### ISSUE TITLE
Incluir regla `strictNullChecks` en tsconfig.json

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#899]
### Descripción

Se requiere la introducción de la regla `strictNullChecks` en `tsconfig.json` para fortalecer el tipado del proyecto.

Este issue se encuentra bloqueado hasta llevar adelante una auditoría de tipos que permita deshacerse de tipos marcados como `null` o `undefined`.

### Recursos

- https://www.typescriptlang.org/tsconfig/#strictNullChecks

**Comment by Jash2606** [comment]
Hola @rolivencia, he creado una PR para esto. ¿Podrías revisarla y decirme si se requieren más cambios?

**Comment by rolivencia** [comment]
Issue is not ready to be worked on and has been marked as blocked. The changes introduced in the related #903 PR causes the application not to build properly, which is a direct cause of the codebase not being ready for this rule to be introduced.
