### ISSUE TITLE
Solucionar problemas en tests de `EpigraphComponent`

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#928]
### Tareas
- [ ] Migrar la implementación del archivo `epigraph.component.spec.ts` de TestBed a Angular Testing Library.
- [ ] Agregar un objeto mock de tipo `Epigraph` para pasar como propiedad al objeto `componentInputs` de la función `render` de Angular Testing Library.
- [ ]  Usar `toBeInTheDocument` en lugar de `toBeTruthy`.
- [ ]  Testear que el `reference` aparezca en el documento.
- [ ] Cambiar la definición de la función `xdescribe` en `describe` antes de crear la pull request vinculada a este issue.

### Recursos
- Revisar otros ejemplos de tests funcionales para tomar como referencia.
- Recordar cambiar `xdescribe` por `describe` para poder correr los tests definidos en `epigraph.component.spec.ts`. Chequear #739 para una descripción más detallada al respecto.
- [Uso de Angular Testing Library](https://testing-library.com/docs/angular-testing-library/examples).

**Comment by dylanson25** [comment]
puedo tomarlo?

**Comment by rolivencia** [comment]
Adelante @dylanson25
