### ISSUE TITLE
Solucionar problemas en tests de `NavigableStoryTeaserComponent`

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#931]
### Tareas
- [ ] Migrar la implementación del archivo `navigable-story-teaser.component.spec.ts` de TestBed a Angular Testing Library.
- [ ] Agregar un objeto mock de tipo `StoryBase` para pasar como propiedad al objeto `componentInputs` de la función `render` de Angular Testing Library.
- [ ] Usar `toBeInTheDocument` en lugar de `toBeTruthy`.
- [ ] Testear que el `title` y el `approximateReadingTime` aparezcan en el documento.
- [ ] Cambiar la definición de la función `xdescribe` en `describe` antes de crear la pull request vinculada a este issue.

### Recursos
- Revisar otros ejemplos de tests funcionales para tomar como referencia.
- Recordar cambiar `xdescribe` por `describe` para poder correr los tests definidos en `navigable-story-teaser.component.spec.ts`. Chequear #739 para una descripción más detallada al respecto.
- [Uso de Angular Testing Library](https://testing-library.com/docs/angular-testing-library/examples).

**Comment by dylanson25** [comment]
Puedo tomar este?
Los demas issues de tests estan marcados como bloquedaos. 
- @rolivencia

**Comment by rolivencia** [comment]
Asignado @dylanson25
