### ISSUE TITLE
Alineación adecuada de los mapas en la sección de Nacionalidad en la 'Bandera' de una nación en particular

### ISSUE THREAD

**Issue by TanviAgarwal-14** [cuentoneta/cuentoneta#937]
### Descripción

![image](https://github.com/user-attachments/assets/4fe8cc96-4b7d-4b4b-aa00-5491e50547f7)

En la imagen podemos ver que la bandera no está alineada correctamente en el centro del cuadro

**Comment by rolivencia** [comment]
La imagen posee las proporciones correctas y la alineación en Sanity Studio se da por el hecho de que todas las imágenes son centradas horizontalmente por la herramienta.

Puede verificarse el tamaño de las banderas en la carpeta `/resources` del proyecto.
