### ISSUE TITLE
README file in English (Archivo README en inglés)

### ISSUE THREAD

**Issue by TanviAgarwal-14** [cuentoneta/cuentoneta#938]
### Descripción

 The current repository has a README file written in Spanish. To make the project more accessible to a global audience, I propose adding a README file in English.

Need:
- 
- The existing README in Spanish may limit the project's reach to non-Spanish speakers.
- An English README will improve accessibility and usability for international contributors and users.
- Benefits:
- 
- Broader Audience: Helps reach more users and contributors who speak English.
- Improved Communication: Facilitates better collaboration in the open-source community.
- Enhanced Documentation: Provides clear and comprehensive project details to a wider audience.
Plan:
- Translate the existing README content from Spanish to English.
- Ensure the translated README maintains the same structure and includes all relevant sections.
-Review and finalize the English README for accuracy.
 I will create and add the new English README file to the repository and will update this issue with the details once the pull request is prepared.

**Comment by rolivencia** [comment]
In the foreseeable future, it's not within the project's goals to support content for non-Spanish readers. Currently, we support content in English, but it's aimed at non-native English speakers.

The code itself is in English. I won't forbid any efforts related to translating the docs to English, but it's not on our list of priorities.
