### ISSUE TITLE
Actualizar versión de Storybook

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#944]
### Descripción

Se requiere actualizar Storybook a una versión compatible con la versión de Angular vigente para el proyecto. Se requiere proceder a la actualización considerando a Storybook como utilidad bajo la órbita de Nx.

Información de pnpm:

```
└─┬ @storybook/angular 7.5.3
  ├── ✕ unmet peer @angular-devkit/build-angular@">=14.1.0 < 18.0.0": found 18.1.2
  ├── ✕ unmet peer @angular/cli@">=14.1.0 < 18.0.0": found 18.1.2
  ├── ✕ unmet peer @angular/common@">=14.1.0 < 18.0.0": found 18.1.2
  ├── ✕ unmet peer @angular/compiler@">=14.1.0 < 18.0.0": found 18.1.2
  ├── ✕ unmet peer @angular/compiler-cli@">=14.1.0 < 18.0.0": found 18.1.2
  ├── ✕ unmet peer @angular/core@">=14.1.0 < 18.0.0": found 18.1.2
  ├── ✕ unmet peer @angular/forms@">=14.1.0 < 18.0.0": found 18.1.2
  ├── ✕ unmet peer @angular/platform-browser@">=14.1.0 < 18.0.0": found 18.1.2
  └── ✕ unmet peer @angular/platform-browser-dynamic@">=14.1.0 < 18.0.0": found 18.1.2
```

**Comment by rolivencia** [comment]
@ErikGIovani, ¿podríamos proceder con este update? ¿te parece que actualice Angular + Nx en estos días y procedemos con este update?

**Comment by ErikGIovani** [comment]
> @ErikGIovani, ¿podríamos proceder con este update? ¿te parece que actualice Angular + Nx en estos días y procedemos con este update?

Será un placer 👍

**Comment by rolivencia** [comment]
Al parecer la versión 19.8 de Nx migra la versión de Storybook a la 8.2.8. Con la actualización de Angular podremos también cubrir este issue.

**Comment by rolivencia** [comment]
El issue ya fue abordado en #1052. Procedo a darle cierre.
