### ISSUE TITLE
Solucionar problemas en tests de `TooltipDirective`

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#945]
### Tareas
- [x] Cambiar la propiedad `componentProperties` del render de el componente `HostComponent` en el archivo `tooltip.directive.spec.ts`.
- [x] Agregar `userEvent` de `@testing-library/user-event` para hacer la interacción con los test parecido a como lo haría un usuario.
- [x] Importar en los imports del componente `HostComponent` la directiva `TooltipDirective`.
- [x] Usar `toBeInTheDocument` en lugar de `toBeTruthy`.
- [x] Cambiar la definición de la función `xdescribe` en `describe` antes de crear la pull request vinculada a este issue.

### Recursos
- Revisar otros ejemplos de tests funcionales para tomar como referencia.
- Recordar cambiar `xdescribe` por `describe` para poder correr los tests definidos en `tooltip.directive.spec.ts`. Chequear #739 para una descripción más detallada al respecto.
- [Uso de Angular Testing Library](https://testing-library.com/docs/angular-testing-library/examples).

**Comment by dylanson25** [comment]
Puedo trabajarlo
@rolivencia

**Comment by rolivencia** [comment]
> Puedo trabajarlo? @rolivencia

Asignado 👍🏻

**Comment by dylanson25** [comment]
Estoy teniendo problemas para realizar este test mas que nada a la hora de que se construye el elemento veo que se genera un `p` con la clase `tooltip-container` pero no veo que meta el texto, No se si la implementacion que estoy haciendo del host component sea correcta si me pudieran apoyar seria de ayuda
```ts
import { Component, input } from '@angular/core';
import { render, screen } from '@testing-library/angular';
import { TooltipDirective } from './tooltip.directive';
import userEvent from '@testing-library/user-event';

const ELEMENT_WIDTH = 500;
const ELEMENT_HEIGHT = 500;

@Component({
	template: `
		<div [style.width.px]="width" [style.height.px]="height" [position]="position" tooltip text="Tooltip test">
			Host component
		</div>
	`,
	standalone: true,
	imports: [TooltipDirective],
	hostDirectives: [TooltipDirective],
})
class HostComponent {
	width = ELEMENT_WIDTH;
	height = ELEMENT_HEIGHT;
	position = input('top');
}

fdescribe('TooltipDirective', () => {
	test('Should render a tooltip when the mouse enter the Host component', async () => {
		await render(HostComponent);

		const hostComponent = screen.getByText(/Host component/);

		await userEvent.hover(hostComponent);

		expect(screen.getByText('Tooltip test')).toBeInTheDocument();

		await userEvent.unhover(hostComponent);
		expect(screen.queryByText('Tooltip test')).not.toBeInTheDocument();
	});
});

```

```html
 <body>
      <div
        id="root0"
        ng-version="18.1.2"
      >
        <div
          style="width: 500px; height: 500px;"
          text="Tooltip test"
          tooltip=""
        >
           Host component
        </div>
      </div>
      <p
        class="tooltip-container"
        style="top: -6px; left: 5px;"
      >
        <span
          class="tooltip-arrow"
          style="left: -1px; bottom: -4px;"
        />
      </p>
    </body>
```

**Comment by rolivencia** [comment]
Lo reviso y te doy una devolución luego @dylanson25

**Comment by erikgiovani** [comment]
@dylanson25 prueba con el componente de esta manera:

```
import { Component, inject, OnInit } from '@angular/core';
import { render, screen } from '@testing-library/angular';
import { TooltipDirective } from './tooltip.directive';
import userEvent from '@testing-library/user-event';

const ELEMENT_WIDTH = 500;
const ELEMENT_HEIGHT = 500;

@Component({
	template: `
		<div [style.width.px]="width" [style.height.px]="height" [>
			<p>Host component</p>
		</div>
	`,
	standalone: true,
	imports: [TooltipDirective],
	hostDirectives: [TooltipDirective],
})
class HostComponent implements OnInit {
	width = ELEMENT_WIDTH;
	height = ELEMENT_HEIGHT;
	private tooltipDirective = inject(TooltipDirective);

	ngOnInit() {
		this.tooltipDirective.text.set('Tooltip test');
		this.tooltipDirective.position.set('bottom');
	}
}

describe('TooltipDirective', () => {
	test('Should render a tooltip when the mouse enter the Host component', async () => {
		await render(HostComponent);

		const hostComponent = screen.getByText(/Host component/);

		await userEvent.hover(hostComponent);

		expect(screen.getByText('Tooltip test')).toBeInTheDocument();

		await userEvent.unhover(hostComponent);
		expect(screen.queryByText('Tooltip test')).not.toBeInTheDocument();
	});
});
```

@rolivencia me menciono que en las directivas aun no se soportan signals inputs y así lo resolvió en otras implementaciones de las directivas con signals 👍

**Comment by erikgiovani** [comment]
Por cierto, lamento tardar en responder, pero es que ya no aparece en el discord las actualizaciones de lo que pasa en el repo y revisando los issues me encontré esto 👌

**Comment by dylanson25** [comment]
@erikgiovani Okas, muchas gracias. Lo reviso :3

**Comment by rolivencia** [comment]
> Por cierto, lamento tardar en responder, pero es que ya no aparece en el discord las actualizaciones de lo que pasa en el repo y revisando los issues me encontré esto 👌

Si te parece podemos reactivarlas, pero dejando todo en el mismo canal y filtrando fuera los commits.

**Comment by erikgiovani** [comment]
> > Por cierto, lamento tardar en responder, pero es que ya no aparece en el discord las actualizaciones de lo que pasa en el repo y revisando los issues me encontré esto 👌
> 
> Si te parece podemos reactivarlas, pero dejando todo en el mismo canal y filtrando fuera los commits.

Suena bien 👌
