### ISSUE TITLE
Solucionar problemas en tests de `BioSummaryCardComponent`

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#946]
### Tareas
- [ ] Refactorizar el objeto `mockAuthor` para que coincida con el tipo `Author` y el objeto `mockStory` para que coincida con el tipo `Story` para pasar como propiedad al objeto `componentInputs` remplazando `componentProperties` de la función `render` de Angular Testing Library.
- [ ] Usar `toBeInTheDocument` en lugar de `toBeTruthy`.
- [ ] Testear que el `country` y el `name` aparezcan en el documento.
- [ ] Cambiar la definición de la función `xdescribe` en `describe` antes de crear la pull request vinculada a este issue.

### Recursos
- Revisar otros ejemplos de tests funcionales para tomar como referencia.
- Recordar cambiar `xdescribe` por `describe` para poder correr los tests definidos en `bio-summary-card.component.spec.ts`. Chequear #739 para una descripción más detallada al respecto.
- [Uso de Angular Testing Library](https://testing-library.com/docs/angular-testing-library/examples).

**Comment by dylanson25** [comment]
@rolivencia Puedo tomarlo?

**Comment by dylanson25** [comment]
@rolivencia Tengo dos preguntás:

1. ¿Esto que está en el BioSummary hace referencia que puede dar el caso de que no exista un autor?
```js
@if (story().author) {
      <section>
	   ...
      </section>
     }
```
2. Para facilitar algunas pruebas me serviría agregar cosas en los componentes, por ejemplo `role="..."`  o `test-id="..." `  que para este caso me serviria agregar un test-id para ubicar el _**country**_ de forma más rápida
```js
<div test-id="..." class="flex flex-col justify-center">
	<p class="inter-body-lg-semibold">{{ story().author.name }}</p>
	<div class="inter-body-base-medium flex items-center gap-2 text-gray-700">
		<img
			[alt]="'Bandera de ' + story().author.nationality.country"
			[ngSrc]="story().author.nationality.flag + '?w=20&h=15'"
			class="h-[15px] w-[20px] rounded"
			width="20"
			height="15"
		/>
		<span>{{ story().author.nationality.country }}</span>
	</div>
</div>
```

**Comment by ErikGIovani** [comment]
> @rolivencia Tengo dos preguntás:
> 
> 1. ¿Esto que está en el BioSummary hace referencia que puede dar el caso de que no exista un autor?
> 
> ```js
> @if (story().author) {
>       <section>
> 	   ...
>       </section>
>      }
> ```
> 
> 2. Para facilitar algunas pruebas me serviría agregar cosas en los componentes, por ejemplo `role="..."`  o `test-id="..." `  que para este caso me serviria agregar un test-id para ubicar el _**country**_ de forma más rápida
> 
> ```js
> <div test-id="..." class="flex flex-col justify-center">
> 	<p class="inter-body-lg-semibold">{{ story().author.name }}</p>
> 	<div class="inter-body-base-medium flex items-center gap-2 text-gray-700">
> 		<img
> 			[alt]="'Bandera de ' + story().author.nationality.country"
> 			[ngSrc]="story().author.nationality.flag + '?w=20&h=15'"
> 			class="h-[15px] w-[20px] rounded"
> 			width="20"
> 			height="15"
> 		/>
> 		<span>{{ story().author.nationality.country }}</span>
> 	</div>
> </div>
> ```

Es correcto 👍

En cuanto al test id por el hecho de usarlo significa que el test no se está haciendo de la manera correcta, puedes testear que el country aparezca dos veces, o para que necesitas específicamente el role o el test id?

**Comment by dylanson25** [comment]
@ErikGIovani 
- Más que nada porque en este caso el **_country_** es México, y si uso el getByText() Puede que no este pero me arroje que si  que coincide con el Mexico que ese encuentra en la biography
- La idea del test-id es por que en realidad no la pondria directamente en el `span` si no en el `div` que la contiene, y de esta forma se podria testear duplicados en ese scope 
- Otra forma que estaba pensando es buscar la etiqueta `<span>country</span>`   
![image](https://github.com/user-attachments/assets/2f25e390-05dc-42a9-b31b-204740c8adfc)

**Comment by rolivencia** [comment]
> @rolivencia Tengo dos preguntás:
> 
> 1. ¿Esto que está en el BioSummary hace referencia que puede dar el caso de que no exista un autor?
> 
> ```js
> @if (story().author) {
>       <section>
> 	   ...
>       </section>
>      }
> ```
> 
> 2. Para facilitar algunas pruebas me serviría agregar cosas en los componentes, por ejemplo `role="..."`  o `test-id="..." `  que para este caso me serviria agregar un test-id para ubicar el _**country**_ de forma más rápida
> 
> ```js
> <div test-id="..." class="flex flex-col justify-center">
> 	<p class="inter-body-lg-semibold">{{ story().author.name }}</p>
> 	<div class="inter-body-base-medium flex items-center gap-2 text-gray-700">
> 		<img
> 			[alt]="'Bandera de ' + story().author.nationality.country"
> 			[ngSrc]="story().author.nationality.flag + '?w=20&h=15'"
> 			class="h-[15px] w-[20px] rounded"
> 			width="20"
> 			height="15"
> 		/>
> 		<span>{{ story().author.nationality.country }}</span>
> 	</div>
> </div>
> ```

1. Esta validación está allí desde hace tiempo y obedece a que anteriormente el tipado en toda la aplicación no era tan estricto como en este momento. Hice una revisión y todos los `@if` en el template de `BioSummaryCardComponent` pueden ser eliminados, a excepción del que valida la longitud del array `resources`: `@if (resources.length > 0)`

2. Existe un componente relativamente reciente, `AuthorTeaserComponent`, que tiene el propósito de abstraer el section en el que se visualizan la imagen del autor, su nombre y su nacionalidad. ¿Podríamos aprovechar a implementarlo en `BioSummaryCardComponent` con una variante en su tamaño para simplificar a qué componente corresponden los tests? Quedo atento a comentarios.

cc @ErikGIovani

**Comment by ErikGIovani** [comment]
> > @rolivencia Tengo dos preguntás:
> > 
> > 1. ¿Esto que está en el BioSummary hace referencia que puede dar el caso de que no exista un autor?
> > 
> > ```js
> > @if (story().author) {
> >       <section>
> > 	   ...
> >       </section>
> >      }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 2. Para facilitar algunas pruebas me serviría agregar cosas en los componentes, por ejemplo `role="..."`  o `test-id="..." `  que para este caso me serviria agregar un test-id para ubicar el _**country**_ de forma más rápida
> > 
> > ```js
> > <div test-id="..." class="flex flex-col justify-center">
> > 	<p class="inter-body-lg-semibold">{{ story().author.name }}</p>
> > 	<div class="inter-body-base-medium flex items-center gap-2 text-gray-700">
> > 		<img
> > 			[alt]="'Bandera de ' + story().author.nationality.country"
> > 			[ngSrc]="story().author.nationality.flag + '?w=20&h=15'"
> > 			class="h-[15px] w-[20px] rounded"
> > 			width="20"
> > 			height="15"
> > 		/>
> > 		<span>{{ story().author.nationality.country }}</span>
> > 	</div>
> > </div>
> > ```
> 
> 1. Esta validación está allí desde hace tiempo y obedece a que anteriormente el tipado en toda la aplicación no era tan estricto como en este momento. Hice una revisión y todos los `@if` en el template de `BioSummaryCardComponent` pueden ser eliminados, a excepción del que valida la longitud del array `resources`: `@if (resources.length > 0)`
> 2. Existe un componente relativamente reciente, `AuthorTeaserComponent`, que tiene el propósito de abstraer el section en el que se visualizan la imagen del autor, su nombre y su nacionalidad. ¿Podríamos aprovechar a implementarlo en `BioSummaryCardComponent` con una variante en su tamaño para simplificar a qué componente corresponden los tests? Quedo atento a comentarios.
> 
> cc @ErikGIovani

Te refieres a en un test pasarle el author y en otro no?

**Comment by ErikGIovani** [comment]
> @ErikGIovani
> 
> * Más que nada porque en este caso el **_country_** es México, y si uso el getByText() Puede que no este pero me arroje que si  que coincide con el Mexico que ese encuentra en la biography
> * La idea del test-id es por que en realidad no la pondria directamente en el `span` si no en el `div` que la contiene, y de esta forma se podria testear duplicados en ese scope
> * Otra forma que estaba pensando es buscar la etiqueta `<span>country</span>`
> 
> ![image](https://private-user-images.githubusercontent.com/54459436/370098182-2f25e390-05dc-42a9-b31b-204740c8adfc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyMDAyNTEsIm5iZiI6MTcyNzE5OTk1MSwicGF0aCI6Ii81NDQ1OTQzNi8zNzAwOTgxODItMmYyNWUzOTAtMDVkYy00MmE5LWIzMWItMjA0NzQwYzhhZGZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDE3NDU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiMGZiNTI3ZWVkYzQ2MjE4NTU1NTVlYzViNjVlYjM5OGQ5MmFhOGJlMzAxZjM2Mjc5MzIzZjI4ZWRiMmQzYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.imseBHk3yEntT_EX3nwOrxWiJHF3Heb6ow7sMmwuYAg)

Pero la data viene de un mock y no afecta al funcionamiento de la app el hecho que existan tres coincidencia del country en el mismo componente, puedes probar en lugar de usar getByText usar queryByText que devolvería un array vacío en caso de no encontrar ninguna coincidencia y eso marcaria error

**Comment by rolivencia** [comment]
> > > @rolivencia Tengo dos preguntás:
> > > 
> > > 1. ¿Esto que está en el BioSummary hace referencia que puede dar el caso de que no exista un autor?
> > > 
> > > ```js
> > > @if (story().author) {
> > >       <section>
> > > 	   ...
> > >       </section>
> > >      }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 
> > > 2. Para facilitar algunas pruebas me serviría agregar cosas en los componentes, por ejemplo `role="..."`  o `test-id="..." `  que para este caso me serviria agregar un test-id para ubicar el _**country**_ de forma más rápida
> > > 
> > > ```js
> > > <div test-id="..." class="flex flex-col justify-center">
> > > 	<p class="inter-body-lg-semibold">{{ story().author.name }}</p>
> > > 	<div class="inter-body-base-medium flex items-center gap-2 text-gray-700">
> > > 		<img
> > > 			[alt]="'Bandera de ' + story().author.nationality.country"
> > > 			[ngSrc]="story().author.nationality.flag + '?w=20&h=15'"
> > > 			class="h-[15px] w-[20px] rounded"
> > > 			width="20"
> > > 			height="15"
> > > 		/>
> > > 		<span>{{ story().author.nationality.country }}</span>
> > > 	</div>
> > > </div>
> > > ```
> > 
> > 
> > 
> > 1. Esta validación está allí desde hace tiempo y obedece a que anteriormente el tipado en toda la aplicación no era tan estricto como en este momento. Hice una revisión y todos los `@if` en el template de `BioSummaryCardComponent` pueden ser eliminados, a excepción del que valida la longitud del array `resources`: `@if (resources.length > 0)`
> > 2. Existe un componente relativamente reciente, `AuthorTeaserComponent`, que tiene el propósito de abstraer el section en el que se visualizan la imagen del autor, su nombre y su nacionalidad. ¿Podríamos aprovechar a implementarlo en `BioSummaryCardComponent` con una variante en su tamaño para simplificar a qué componente corresponden los tests? Quedo atento a comentarios.
> > 
> > cc @ErikGIovani
> 
> Te refieres a en un test pasarle el author y en otro no?

No, me refiero a reformular el template de `BioSummaryCardComponent` abstrayendo la sección de datos que pertenecen específicamente al nombre, imagen y nacionalidad del autor; datos que se muestran de una forma muy similar en `AuthorTeaserComponent`. De esta manera tendríamos un tag extra para poder dirigir el selector de la Testing Library en el test.

Reitero por si no se entendió en mi comentario anterior: ahora puede asegurarse que todas las instancias de `Story` tendrán un `Author` asignado.

**Comment by dylanson25** [comment]
- Eliminare en un commit los `@if` redundantes con excepción de `@if (resources.length > 0)` 

Sobre el punto 2 si lo deciden hacer ya seria en otro issue. Verdad?? 

 
 cc: @rolivencia

**Comment by rolivencia** [comment]
> * Eliminare en un commit los `@if` redundantes con excepción de `@if (resources.length > 0)`
> 
> Sobre el punto 2 si lo deciden hacer ya seria en otro issue. Verdad??
> 
> cc: @rolivencia

Sí, sería lo ideal. Si quieres puedes agregarlo y taggearme.

**Comment by rolivencia** [comment]
Abordados ya los requerimientos definidos en #1030:
1. Abstraer la información del autor usando un variant de `AuthorTeaserComponent` en `BioSummaryCardComponent`.
2. Eliminados todos los `@if` redundantes en el template de `BioSummaryCardComponent`

Actualiza tu branch con los últimos cambios disponibles en `develop` @dylanson25.
