### ISSUE TITLE
Solucionar problemas en tests de `PublicationCardComponent`

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#949]
### Tareas
- [ ] Agregar un objeto mock de tipo `Publication<StoryPreview>`, y uno de tipo `UrlTree` para pasar como propiedad al objeto `componentInputs` de la función `render` de Angular Testing Library.
- [ ] Usar `toBeInTheDocument` en lugar de `toBeTruthy`.
- [ ] Cambiar la definición de la función `xdescribe` en `describe` antes de crear la pull request vinculada a este issue.

### Recursos
- Revisar otros ejemplos de tests funcionales para tomar como referencia.
- Recordar cambiar `xdescribe` por `describe` para poder correr los tests definidos en `publication-card.component.spec.ts`. Chequear #739 para una descripción más detallada al respecto.
- [Uso de Angular Testing Library](https://testing-library.com/docs/angular-testing-library/examples).

**Comment by rolivencia** [comment]
> Puedo tomarlo
> @rolivencia 

Asignado 🤝

**Comment by dylanson25** [comment]
En que parte de la aplicacion se puede ver el componente de `PublicationCardComponent` dentro de la pagina?

- @rolivencia

**Comment by rolivencia** [comment]
> En que parte de la aplicacion se puede ver el componente de `PublicationCardComponent` dentro de la pagina?
> 
> * @rolivencia

Dentro de cualquier storylist. Son las tarjetas que representan a las historias al navegar a una storylist particular. Por ejemplo: https://www.cuentoneta.ar/storylist/cuentos-de-terror-de-alberto-laiseca
