### ISSUE TITLE
Solucionar problemas en tests de `StoryCardComponent`

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#950]
### Tareas
- [ ] Migrar la implementación del archivo `story-card.component.spec.ts` de TestBed a Angular Testing Library.
- [ ] Agregar un objeto mock de tipo `StoryPreview` para pasar como propiedad al objeto `componentInputs` de la función `render` de Angular Testing Library. Buscar la constante `mockStoryPreview` disponible en `story.mocks.ts` para ello.
- [ ] Usar `toBeInTheDocument` en lugar de `toBeTruthy`.
- [ ] Testear que `approximateReadingTime` aparezca en el documento.
- [ ] Cambiar la definición de la función `xdescribe` en `describe` antes de crear la pull request vinculada a este issue.

### Recursos
- Revisar otros ejemplos de tests funcionales para tomar como referencia.
- Recordar cambiar `xdescribe` por `describe` para poder correr los tests definidos en `story-card.component.spec.ts`. Chequear #739 para una descripción más detallada al respecto.
- [Uso de Angular Testing Library](https://testing-library.com/docs/angular-testing-library/examples).

**Comment by dylanson25** [comment]
@rolivencia Me podrias asignar este issue?

**Comment by rolivencia** [comment]
Asignado. Puedes acercar tus consultas por aquí o en el canal de Discord @dylanson25.

**Comment by dylanson25** [comment]
@rolivencia 

En el issue: https://github.com/cuentoneta/cuentoneta/issues/995 se modifico el input navigationRoute para ser requerido.
Existe algun mock para navigationRoute?  O lo manejo de otra forma?

**Comment by rolivencia** [comment]
> @rolivencia
> 
> En el issue: #995 se modifico el input navigationRoute para ser requerido. Existe algun mock para navigationRoute? O lo manejo de otra forma?

Puedes hacer uso de este código para crear un UrlTree que concuerde con los datos que tenemos en los mocks y así pasarlo como input para `navigationRoute`:

```typescript
const mockNavigationRoute = this.router.createUrlTree(['/', 'story', 'el-espejo-del-tiempo'], { queryParams: { navigation: 'author', navigationSlug: 'francois-onoff' } }),
````
