### ISSUE TITLE
Determinar solución para error `Error: Could not parse CSS stylesheet` en ejecución de Jest.

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#952]

**Comment by ErikGIovani** [comment]
> _No description provided._

Encontré varias posibles soluciones: https://stackoverflow.com/questions/69906136/console-error-error-could-not-parse-css-stylesheet

**Comment by rolivencia** [comment]
> > _No description provided._
> 
> Encontré varias posibles soluciones: https://stackoverflow.com/questions/69906136/console-error-error-could-not-parse-css-stylesheet

Creo que [esta de aquí](https://github.com/primefaces/primeng/issues/14085) puede ser una mejor solución.
