### ISSUE TITLE
Generar template de PR para despliegue en producción

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#961]
### Descripción

Generar una template para las PR para el despliegue a la rama `master`. Utilizar como título "[RELEASE] - Despliegue a producción vx.x.x"

### Recursos

Crear templates para PRs: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

**Comment by aizaysi** [comment]
is this an issue???
what's wrong here?

**Comment by rolivencia** [comment]
> is this an issue??? what's wrong here?

It is. The description is to be completed later. This issue is related to the creation of a PR template that'll be used for merges from `develop` to `master`. It was lacking the `✍🏻 bosquejo` label.
