### ISSUE TITLE
Incluir stylelint en el proyecto

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#962]
### Descripción

Agregar stylelint (y una Github Action relacionada) al proyecto, a fin de consolidar una forma estructurada de escribir el código SCSS.

### Tareas

- [x] Agregar `stylelint` a dependencias (ver recursos) (abordado en #983)
- [x] #980
- [x] Generar Github Action con una corrida de `stylelint`.
- [x] #1000

### Recursos

- https://stylelint.io/user-guide/get-started/
- Plugin de Stylelint para Nx: https://www.npmjs.com/package/nx-stylelint

**Comment by rolivencia** [comment]
¿Te interesaría revisar este @Addin?

**Comment by Addin** [comment]
Me interesa, es un issue interesante.

**Comment by rolivencia** [comment]
Agregué a los recursos el plugin de Stylelint para Nx, el cual encontré viendo cómo soportar los estilos inline. Tal vez deberíamos reformular el trabajo del issue tomando en cuenta el plugin @Addin @ErikGIovani.

**Comment by Addin** [comment]
Sin ningún problema, esta integración con NX va a ser mucho mejor y si resuelve el problema de los estilos inline, vamos a darle con esa entonces.

**Comment by rolivencia** [comment]
Procedo a cerrar el issue dado que todos los issues derivados y tareas ya han sido completados.
