### ISSUE TITLE
Ocultar labels vacías en `NavigableStoryTeaserComponent`

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#971]
### ¿Existe un problema similar reportado?

- [ ] Existe un problema similar
- [ ] Es un problema completamente nuevo

### Descripción del problema

Al acceder a la vista de lectura de una story con navegación de otras obras del autor (por ejemplo, [aquí Fontanarrosa](https://www.cuentoneta.ar/story/la-yacuareguazu?navigation=author&navigationSlug=roberto-fontanarrosa) ) se muestra la label superior vacía, con sólo el borde vertical izquierdo visible.

### Pasos para reproducir el problema

1. Ir a https://www.cuentoneta.ar/story/la-yacuareguazu?navigation=author&navigationSlug=roberto-fontanarrosa
2. Ver que no se visualiza ningún texto en el label superior.

### Comportamiento esperado

Debería ocultarse este label cuando no hay texto para mostrar

### Capturas de pantalla

![image](https://github.com/user-attachments/assets/a654d057-4188-401d-8f5d-bdf31a3cb0ab)

### Información adicional / Recursos

Probablemente el problema pueda ser resuelto de manera sencilla al incluir un rendering condicional para los casos en los que el campo `originalPublication` no esté definido en el template de `NavigableStoryTeaser`.

**Comment by felipehmora** [comment]
Hola, creo que puedo trabajar este issue

**Comment by rolivencia** [comment]
> Hola, creo que puedo trabajar este issue

Adelante, te lo asigno.

**Comment by rolivencia** [comment]
You can work on this one if you're interested @Demon-Sheriff

**Comment by Demon-Sheriff** [comment]
@rolivencia Yeah sure, I would like to work on it.

**Comment by rolivencia** [comment]
Just assigned it @Demon-Sheriff. You can check at the comments in #982 for further guidance.

**Comment by rolivencia** [comment]
Hi @Demon-Sheriff! Do you have any news on this one? Do not hesitate to ask if you need any help.

**Comment by Demon-Sheriff** [comment]
Hey @rolivencia , thank you for being patient , I have been involved with competitive programming for a while now, so really sorry that I almost completely forgot about this issue, I think I have a solution for this one so I am raising a PR #1016 ,  waiting for any further updates :smile:

**Comment by rolivencia** [comment]
> Hey @rolivencia , thank you for being patient , I have been involved with competitive programming for a while now, so really sorry that I almost completely forgot about this issue, I think I have a solution for this one so I am raising a PR #1016 , waiting for any further updates 😄

No worries, and it's great to hear from you. I hope the competition went well. Please check the comment in #1016 regarding this issue. It seems it was solved, probably from one of the big PRs I set up a couple weeks ago.

**Comment by rolivencia** [comment]
Cierro el issue debido a que el problema ya fue abordado.

**Comment by Demon-Sheriff** [comment]
> > Hey @rolivencia , thank you for being patient , I have been involved with competitive programming for a while now, so really sorry that I almost completely forgot about this issue, I think I have a solution for this one so I am raising a PR #1016 , waiting for any further updates 😄
> 
> No worries, and it's great to hear from you. I hope the competition went well. Please check the comment in #1016 regarding this issue. It seems it was solved, probably from one of the big PRs I set up a couple weeks ago.

Alright, I have requested for resources on `signal-based inputs` in #1016.
