### ISSUE TITLE
Agregar automáticamente el tag "bosquejo" a los issues nuevos

### ISSUE THREAD

**Issue by rolivencia** [cuentoneta/cuentoneta#991]
### Descripción

Dado que por lo general los issues se crean a partir de una idea inacabada del trabajo a realizar para, posteriormente, proceder a detallar con mayor precisión su contenido, alcance y criterios de aceptación, se hace necesario modificar todos los issue templates para que, automáticamente, sean creados con el tag `✍️ bosquejo`.

En caso de que la primera definición del issue sea detallada, el tag puede ser removido al momento de la creación.

### Recursos

Revisar definiciones de issue templates en los archivos `*.yml` dentro del directorio `.github/ISSUE_TEMPLATE`

**Comment by Demon-Sheriff** [comment]
hey @rolivencia , is this ready to be worked on, if so then I would like to pick it up.

**Comment by Demon-Sheriff** [comment]
hey @rolivencia, this one is done right, just asking because this one is tagged open still.

**Comment by Demon-Sheriff** [comment]
> hey @rolivencia, this one is done right, just asking because this one is tagged open still.

Also I would like to contribute to more issues here as well but I dont have much experience with typescript, I have worked with javascripts projects though, what would be a good starting point ?
